# Generated by Django 2.0.2 on 2018-02-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_exponent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='data',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
